// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/firestore/v1/query_profile.proto

package com.google.firestore.v1;

public interface QueryPlanOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.firestore.v1.QueryPlan)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Planning phase information for the query. It will include:
   *
   * {
   *   "indexes_used": [
   *     {"query_scope": "Collection", "properties": "(foo ASC, __name__ ASC)"},
   *     {"query_scope": "Collection", "properties": "(bar ASC, __name__ ASC)"}
   *   ]
   * }
   * </pre>
   *
   * <code>.google.protobuf.Struct plan_info = 1;</code>
   * @return Whether the planInfo field is set.
   */
  boolean hasPlanInfo();
  /**
   * <pre>
   * Planning phase information for the query. It will include:
   *
   * {
   *   "indexes_used": [
   *     {"query_scope": "Collection", "properties": "(foo ASC, __name__ ASC)"},
   *     {"query_scope": "Collection", "properties": "(bar ASC, __name__ ASC)"}
   *   ]
   * }
   * </pre>
   *
   * <code>.google.protobuf.Struct plan_info = 1;</code>
   * @return The planInfo.
   */
  com.google.protobuf.Struct getPlanInfo();
  /**
   * <pre>
   * Planning phase information for the query. It will include:
   *
   * {
   *   "indexes_used": [
   *     {"query_scope": "Collection", "properties": "(foo ASC, __name__ ASC)"},
   *     {"query_scope": "Collection", "properties": "(bar ASC, __name__ ASC)"}
   *   ]
   * }
   * </pre>
   *
   * <code>.google.protobuf.Struct plan_info = 1;</code>
   */
  com.google.protobuf.StructOrBuilder getPlanInfoOrBuilder();
}
