// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/firestore/v1/query_profile.proto

package com.google.firestore.v1;

public interface ResultSetStatsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.firestore.v1.ResultSetStats)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Plan for the query.
   * </pre>
   *
   * <code>.google.firestore.v1.QueryPlan query_plan = 1;</code>
   * @return Whether the queryPlan field is set.
   */
  boolean hasQueryPlan();
  /**
   * <pre>
   * Plan for the query.
   * </pre>
   *
   * <code>.google.firestore.v1.QueryPlan query_plan = 1;</code>
   * @return The queryPlan.
   */
  com.google.firestore.v1.QueryPlan getQueryPlan();
  /**
   * <pre>
   * Plan for the query.
   * </pre>
   *
   * <code>.google.firestore.v1.QueryPlan query_plan = 1;</code>
   */
  com.google.firestore.v1.QueryPlanOrBuilder getQueryPlanOrBuilder();

  /**
   * <pre>
   * Aggregated statistics from the execution of the query.
   *
   * This will only be present when the request specifies `PROFILE` mode.
   * For example, a query will return the statistics including:
   *
   * {
   *   "results_returned": "20",
   *   "documents_scanned": "20",
   *   "indexes_entries_scanned": "10050",
   *   "total_execution_time": "100.7 msecs"
   * }
   * </pre>
   *
   * <code>.google.protobuf.Struct query_stats = 2;</code>
   * @return Whether the queryStats field is set.
   */
  boolean hasQueryStats();
  /**
   * <pre>
   * Aggregated statistics from the execution of the query.
   *
   * This will only be present when the request specifies `PROFILE` mode.
   * For example, a query will return the statistics including:
   *
   * {
   *   "results_returned": "20",
   *   "documents_scanned": "20",
   *   "indexes_entries_scanned": "10050",
   *   "total_execution_time": "100.7 msecs"
   * }
   * </pre>
   *
   * <code>.google.protobuf.Struct query_stats = 2;</code>
   * @return The queryStats.
   */
  com.google.protobuf.Struct getQueryStats();
  /**
   * <pre>
   * Aggregated statistics from the execution of the query.
   *
   * This will only be present when the request specifies `PROFILE` mode.
   * For example, a query will return the statistics including:
   *
   * {
   *   "results_returned": "20",
   *   "documents_scanned": "20",
   *   "indexes_entries_scanned": "10050",
   *   "total_execution_time": "100.7 msecs"
   * }
   * </pre>
   *
   * <code>.google.protobuf.Struct query_stats = 2;</code>
   */
  com.google.protobuf.StructOrBuilder getQueryStatsOrBuilder();
}
