docker:
  image: "gcr.io/cloud-devrel-public-resources/owlbot-java:latest"

deep-remove-regex:
- "/grpc-google-.*/src"
- "/proto-google-.*/src"
- "/google-cloud-firestore/src/.*/java/com/google/cloud/firestore/v1/"
- "/google-cloud-firestore-admin/src"

deep-preserve-regex:
- "/google-.*/src/test/java/com/google/cloud/.*/v.*/it/IT.*Test.java"
- "/proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/DocumentPathName.java"
- "/proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/AnyPathName.java"
- "/proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/DatabaseRootName.java"
- "/proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/DocumentRootName.java"
- "/proto-google-cloud-firestore-admin-v1/src/main/java/com/google/firestore/admin/v1/ParentName.java"
- "/proto-google-cloud-firestore-v1/src/main/proto/firestore"

deep-copy-regex:
- source: "/google/firestore/(v\\d)/.*-java/proto-google-.*/src"
  dest: "/owl-bot-staging/$1/proto-google-cloud-firestore-$1/src"
- source: "/google/firestore/(v\\d)/.*-java/grpc-google-.*/src"
  dest: "/owl-bot-staging/$1/grpc-google-cloud-firestore-$1/src"
- source: "/google/firestore/(v\\d)/.*-java/gapic-google-.*/src"
  dest: "/owl-bot-staging/$1/google-cloud-firestore/src"
- source: "/google/firestore/admin/(v\\d)/.*-java/proto-google-.*/src"
  dest: "/owl-bot-staging/$1/proto-google-cloud-firestore-admin-$1/src"
- source: "/google/firestore/admin/(v\\d)/.*-java/grpc-google-.*/src"
  dest: "/owl-bot-staging/$1/grpc-google-cloud-firestore-admin-$1/src"
- source: "/google/firestore/admin/(v\\d)/.*-java/gapic-google-.*/src"
  dest: "/owl-bot-staging/$1/google-cloud-firestore-admin/src"
- source: "/google/firestore/bundle/google-cloud-firestore-bundle-v1-java/proto-google-cloud-firestore-bundle-v1-java/src"
  dest: "/owl-bot-staging/v1/proto-google-cloud-firestore-bundle-v1/src"
