// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/firestore/admin/v1/firestore_admin.proto

// Protobuf Java Version: 3.25.3
package com.google.firestore.admin.v1;

public interface BulkDeleteDocumentsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.firestore.admin.v1.BulkDeleteDocumentsResponse)
    com.google.protobuf.MessageOrBuilder {
}
