// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/firestore/admin/v1/firestore_admin.proto

package com.google.firestore.admin.v1;

public interface CreateIndexRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.firestore.admin.v1.CreateIndexRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required. A parent name of the form
   * `projects/{project_id}/databases/{database_id}/collectionGroups/{collection_id}`
   * </pre>
   *
   * <code>string parent = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
   * @return The parent.
   */
  java.lang.String getParent();
  /**
   * <pre>
   * Required. A parent name of the form
   * `projects/{project_id}/databases/{database_id}/collectionGroups/{collection_id}`
   * </pre>
   *
   * <code>string parent = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
   * @return The bytes for parent.
   */
  com.google.protobuf.ByteString
      getParentBytes();

  /**
   * <pre>
   * Required. The composite index to create.
   * </pre>
   *
   * <code>.google.firestore.admin.v1.Index index = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the index field is set.
   */
  boolean hasIndex();
  /**
   * <pre>
   * Required. The composite index to create.
   * </pre>
   *
   * <code>.google.firestore.admin.v1.Index index = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The index.
   */
  com.google.firestore.admin.v1.Index getIndex();
  /**
   * <pre>
   * Required. The composite index to create.
   * </pre>
   *
   * <code>.google.firestore.admin.v1.Index index = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  com.google.firestore.admin.v1.IndexOrBuilder getIndexOrBuilder();
}
