// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/firestore/admin/v1/database.proto

package com.google.firestore.admin.v1;

public final class DatabaseProto {
  private DatabaseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_firestore_admin_v1_Database_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_admin_v1_Database_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(google/firestore/admin/v1/database.pro" +
      "to\022\031google.firestore.admin.v1\032\037google/ap" +
      "i/field_behavior.proto\032\031google/api/resou" +
      "rce.proto\032\036google/protobuf/duration.prot" +
      "o\032\037google/protobuf/timestamp.proto\"\341\010\n\010D" +
      "atabase\022\014\n\004name\030\001 \001(\t\022\023\n\013location_id\030\t \001" +
      "(\t\022>\n\004type\030\n \001(\01620.google.firestore.admi" +
      "n.v1.Database.DatabaseType\022M\n\020concurrenc" +
      "y_mode\030\017 \001(\01623.google.firestore.admin.v1" +
      ".Database.ConcurrencyMode\022A\n\030version_ret" +
      "ention_period\030\021 \001(\0132\031.google.protobuf.Du" +
      "rationB\004\342A\001\003\022?\n\025earliest_version_time\030\022 " +
      "\001(\0132\032.google.protobuf.TimestampB\004\342A\001\003\022l\n" +
      "!point_in_time_recovery_enablement\030\025 \001(\016" +
      "2A.google.firestore.admin.v1.Database.Po" +
      "intInTimeRecoveryEnablement\022a\n\033app_engin" +
      "e_integration_mode\030\023 \001(\0162<.google.firest" +
      "ore.admin.v1.Database.AppEngineIntegrati" +
      "onMode\022\030\n\nkey_prefix\030\024 \001(\tB\004\342A\001\003\022\014\n\004etag" +
      "\030c \001(\t\"W\n\014DatabaseType\022\035\n\031DATABASE_TYPE_" +
      "UNSPECIFIED\020\000\022\024\n\020FIRESTORE_NATIVE\020\001\022\022\n\016D" +
      "ATASTORE_MODE\020\002\"w\n\017ConcurrencyMode\022 \n\034CO" +
      "NCURRENCY_MODE_UNSPECIFIED\020\000\022\016\n\nOPTIMIST" +
      "IC\020\001\022\017\n\013PESSIMISTIC\020\002\022!\n\035OPTIMISTIC_WITH" +
      "_ENTITY_GROUPS\020\003\"\233\001\n\035PointInTimeRecovery" +
      "Enablement\0221\n-POINT_IN_TIME_RECOVERY_ENA" +
      "BLEMENT_UNSPECIFIED\020\000\022\"\n\036POINT_IN_TIME_R" +
      "ECOVERY_ENABLED\020\001\022#\n\037POINT_IN_TIME_RECOV" +
      "ERY_DISABLED\020\002\"b\n\030AppEngineIntegrationMo" +
      "de\022+\n\'APP_ENGINE_INTEGRATION_MODE_UNSPEC" +
      "IFIED\020\000\022\013\n\007ENABLED\020\001\022\014\n\010DISABLED\020\002:R\352AO\n" +
      "!firestore.googleapis.com/Database\022\'proj" +
      "ects/{project}/databases/{database}R\001\001B\334" +
      "\001\n\035com.google.firestore.admin.v1B\rDataba" +
      "seProtoP\001Z9cloud.google.com/go/firestore" +
      "/apiv1/admin/adminpb;adminpb\242\002\004GCFS\252\002\037Go" +
      "ogle.Cloud.Firestore.Admin.V1\312\002\037Google\\C" +
      "loud\\Firestore\\Admin\\V1\352\002#Google::Cloud:" +
      ":Firestore::Admin::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.FieldBehaviorProto.getDescriptor(),
          com.google.api.ResourceProto.getDescriptor(),
          com.google.protobuf.DurationProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_google_firestore_admin_v1_Database_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_firestore_admin_v1_Database_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_firestore_admin_v1_Database_descriptor,
        new java.lang.String[] { "Name", "LocationId", "Type", "ConcurrencyMode", "VersionRetentionPeriod", "EarliestVersionTime", "PointInTimeRecoveryEnablement", "AppEngineIntegrationMode", "KeyPrefix", "Etag", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.ResourceProto.resource);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
