// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/firestore/admin/v1/firestore_admin.proto

// Protobuf Java Version: 3.25.2
package com.google.firestore.admin.v1;

public interface DeleteBackupScheduleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.firestore.admin.v1.DeleteBackupScheduleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required. The name of backup schedule.
   *
   * Format
   * `projects/{project}/databases/{database}/backupSchedules/{backup_schedule}`
   * </pre>
   *
   * <code>string name = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Required. The name of backup schedule.
   *
   * Format
   * `projects/{project}/databases/{database}/backupSchedules/{backup_schedule}`
   * </pre>
   *
   * <code>string name = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
