// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/firestore/admin/v1/firestore_admin.proto

package com.google.firestore.admin.v1;

public interface DeleteDatabaseMetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.firestore.admin.v1.DeleteDatabaseMetadata)
    com.google.protobuf.MessageOrBuilder {
}
