// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/firestore/admin/v1/field.proto

package com.google.firestore.admin.v1;

public final class FieldProto {
  private FieldProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_firestore_admin_v1_Field_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_admin_v1_Field_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_firestore_admin_v1_Field_IndexConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_admin_v1_Field_IndexConfig_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%google/firestore/admin/v1/field.proto\022" +
      "\031google.firestore.admin.v1\032\037google/api/f" +
      "ield_behavior.proto\032\031google/api/resource" +
      ".proto\032%google/firestore/admin/v1/index." +
      "proto\032\034google/api/annotations.proto\"\345\002\n\005" +
      "Field\022\021\n\004name\030\001 \001(\tB\003\340A\002\022B\n\014index_config" +
      "\030\002 \001(\0132,.google.firestore.admin.v1.Field" +
      ".IndexConfig\032\211\001\n\013IndexConfig\0221\n\007indexes\030" +
      "\001 \003(\0132 .google.firestore.admin.v1.Index\022" +
      "\034\n\024uses_ancestor_config\030\002 \001(\010\022\026\n\016ancesto" +
      "r_field\030\003 \001(\t\022\021\n\treverting\030\004 \001(\010:y\352Av\n\036f" +
      "irestore.googleapis.com/Field\022Tprojects/" +
      "{project}/databases/{database}/collectio" +
      "nGroups/{collection}/fields/{field}B\336\001\n\035" +
      "com.google.firestore.admin.v1B\nFieldProt" +
      "oP\001Z>google.golang.org/genproto/googleap" +
      "is/firestore/admin/v1;admin\242\002\004GCFS\252\002\037Goo" +
      "gle.Cloud.Firestore.Admin.V1\312\002\037Google\\Cl" +
      "oud\\Firestore\\Admin\\V1\352\002#Google::Cloud::" +
      "Firestore::Admin::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.FieldBehaviorProto.getDescriptor(),
          com.google.api.ResourceProto.getDescriptor(),
          com.google.firestore.admin.v1.IndexProto.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
        });
    internal_static_google_firestore_admin_v1_Field_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_firestore_admin_v1_Field_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_firestore_admin_v1_Field_descriptor,
        new java.lang.String[] { "Name", "IndexConfig", });
    internal_static_google_firestore_admin_v1_Field_IndexConfig_descriptor =
      internal_static_google_firestore_admin_v1_Field_descriptor.getNestedTypes().get(0);
    internal_static_google_firestore_admin_v1_Field_IndexConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_firestore_admin_v1_Field_IndexConfig_descriptor,
        new java.lang.String[] { "Indexes", "UsesAncestorConfig", "AncestorField", "Reverting", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.ResourceProto.resource);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.firestore.admin.v1.IndexProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
