// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/firestore/admin/v1/firestore_admin.proto

package com.google.firestore.admin.v1;

public final class FirestoreAdminProto {
  private FirestoreAdminProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_firestore_admin_v1_ListDatabasesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_admin_v1_ListDatabasesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_firestore_admin_v1_CreateDatabaseRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_admin_v1_CreateDatabaseRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_firestore_admin_v1_CreateDatabaseMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_admin_v1_CreateDatabaseMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_firestore_admin_v1_ListDatabasesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_admin_v1_ListDatabasesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_firestore_admin_v1_GetDatabaseRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_admin_v1_GetDatabaseRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_firestore_admin_v1_UpdateDatabaseRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_admin_v1_UpdateDatabaseRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_firestore_admin_v1_UpdateDatabaseMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_admin_v1_UpdateDatabaseMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_firestore_admin_v1_DeleteDatabaseRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_admin_v1_DeleteDatabaseRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_firestore_admin_v1_DeleteDatabaseMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_admin_v1_DeleteDatabaseMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_firestore_admin_v1_CreateIndexRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_admin_v1_CreateIndexRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_firestore_admin_v1_ListIndexesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_admin_v1_ListIndexesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_firestore_admin_v1_ListIndexesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_admin_v1_ListIndexesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_firestore_admin_v1_GetIndexRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_admin_v1_GetIndexRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_firestore_admin_v1_DeleteIndexRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_admin_v1_DeleteIndexRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_firestore_admin_v1_UpdateFieldRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_admin_v1_UpdateFieldRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_firestore_admin_v1_GetFieldRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_admin_v1_GetFieldRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_firestore_admin_v1_ListFieldsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_admin_v1_ListFieldsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_firestore_admin_v1_ListFieldsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_admin_v1_ListFieldsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_firestore_admin_v1_ExportDocumentsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_admin_v1_ExportDocumentsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_firestore_admin_v1_ImportDocumentsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_admin_v1_ImportDocumentsRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n/google/firestore/admin/v1/firestore_ad" +
      "min.proto\022\031google.firestore.admin.v1\032\034go" +
      "ogle/api/annotations.proto\032\027google/api/c" +
      "lient.proto\032\037google/api/field_behavior.p" +
      "roto\032\031google/api/resource.proto\032(google/" +
      "firestore/admin/v1/database.proto\032%googl" +
      "e/firestore/admin/v1/field.proto\032%google" +
      "/firestore/admin/v1/index.proto\032)google/" +
      "firestore/admin/v1/operation.proto\032#goog" +
      "le/longrunning/operations.proto\032\033google/" +
      "protobuf/empty.proto\032 google/protobuf/fi" +
      "eld_mask.proto\032\037google/protobuf/timestam" +
      "p.proto\"R\n\024ListDatabasesRequest\022:\n\006paren" +
      "t\030\001 \001(\tB*\342A\001\002\372A#\022!firestore.googleapis.c" +
      "om/Database\"\253\001\n\025CreateDatabaseRequest\022:\n" +
      "\006parent\030\001 \001(\tB*\342A\001\002\372A#\022!firestore.google" +
      "apis.com/Database\022;\n\010database\030\002 \001(\0132#.go" +
      "ogle.firestore.admin.v1.DatabaseB\004\342A\001\002\022\031" +
      "\n\013database_id\030\003 \001(\tB\004\342A\001\002\"\030\n\026CreateDatab" +
      "aseMetadata\"d\n\025ListDatabasesResponse\0226\n\t" +
      "databases\030\001 \003(\0132#.google.firestore.admin" +
      ".v1.Database\022\023\n\013unreachable\030\003 \003(\t\"N\n\022Get" +
      "DatabaseRequest\0228\n\004name\030\001 \001(\tB*\342A\001\002\372A#\n!" +
      "firestore.googleapis.com/Database\"\205\001\n\025Up" +
      "dateDatabaseRequest\022;\n\010database\030\001 \001(\0132#." +
      "google.firestore.admin.v1.DatabaseB\004\342A\001\002" +
      "\022/\n\013update_mask\030\002 \001(\0132\032.google.protobuf." +
      "FieldMask\"\030\n\026UpdateDatabaseMetadata\"_\n\025D" +
      "eleteDatabaseRequest\0228\n\004name\030\001 \001(\tB*\342A\001\002" +
      "\372A#\n!firestore.googleapis.com/Database\022\014" +
      "\n\004etag\030\003 \001(\t\"\030\n\026DeleteDatabaseMetadata\"\216" +
      "\001\n\022CreateIndexRequest\022A\n\006parent\030\001 \001(\tB1\342" +
      "A\001\002\372A*\n(firestore.googleapis.com/Collect" +
      "ionGroup\0225\n\005index\030\002 \001(\0132 .google.firesto" +
      "re.admin.v1.IndexB\004\342A\001\002\"\216\001\n\022ListIndexesR" +
      "equest\022A\n\006parent\030\001 \001(\tB1\342A\001\002\372A*\n(firesto" +
      "re.googleapis.com/CollectionGroup\022\016\n\006fil" +
      "ter\030\002 \001(\t\022\021\n\tpage_size\030\003 \001(\005\022\022\n\npage_tok" +
      "en\030\004 \001(\t\"a\n\023ListIndexesResponse\0221\n\007index" +
      "es\030\001 \003(\0132 .google.firestore.admin.v1.Ind" +
      "ex\022\027\n\017next_page_token\030\002 \001(\t\"H\n\017GetIndexR" +
      "equest\0225\n\004name\030\001 \001(\tB\'\342A\001\002\372A \n\036firestore" +
      ".googleapis.com/Index\"K\n\022DeleteIndexRequ" +
      "est\0225\n\004name\030\001 \001(\tB\'\342A\001\002\372A \n\036firestore.go" +
      "ogleapis.com/Index\"|\n\022UpdateFieldRequest" +
      "\0225\n\005field\030\001 \001(\0132 .google.firestore.admin" +
      ".v1.FieldB\004\342A\001\002\022/\n\013update_mask\030\002 \001(\0132\032.g" +
      "oogle.protobuf.FieldMask\"H\n\017GetFieldRequ" +
      "est\0225\n\004name\030\001 \001(\tB\'\342A\001\002\372A \n\036firestore.go" +
      "ogleapis.com/Field\"\215\001\n\021ListFieldsRequest" +
      "\022A\n\006parent\030\001 \001(\tB1\342A\001\002\372A*\n(firestore.goo" +
      "gleapis.com/CollectionGroup\022\016\n\006filter\030\002 " +
      "\001(\t\022\021\n\tpage_size\030\003 \001(\005\022\022\n\npage_token\030\004 \001" +
      "(\t\"_\n\022ListFieldsResponse\0220\n\006fields\030\001 \003(\013" +
      "2 .google.firestore.admin.v1.Field\022\027\n\017ne" +
      "xt_page_token\030\002 \001(\t\"\317\001\n\026ExportDocumentsR" +
      "equest\0228\n\004name\030\001 \001(\tB*\342A\001\002\372A#\n!firestore" +
      ".googleapis.com/Database\022\026\n\016collection_i" +
      "ds\030\002 \003(\t\022\031\n\021output_uri_prefix\030\003 \001(\t\022\025\n\rn" +
      "amespace_ids\030\004 \003(\t\0221\n\rsnapshot_time\030\005 \001(" +
      "\0132\032.google.protobuf.Timestamp\"\233\001\n\026Import" +
      "DocumentsRequest\0228\n\004name\030\001 \001(\tB*\342A\001\002\372A#\n" +
      "!firestore.googleapis.com/Database\022\026\n\016co" +
      "llection_ids\030\002 \003(\t\022\030\n\020input_uri_prefix\030\003" +
      " \001(\t\022\025\n\rnamespace_ids\030\004 \003(\t2\251\026\n\016Firestor" +
      "eAdmin\022\333\001\n\013CreateIndex\022-.google.firestor" +
      "e.admin.v1.CreateIndexRequest\032\035.google.l" +
      "ongrunning.Operation\"~\312A\037\n\005Index\022\026IndexO" +
      "perationMetadata\332A\014parent,index\202\323\344\223\002G\">/" +
      "v1/{parent=projects/*/databases/*/collec" +
      "tionGroups/*}/indexes:\005index\022\275\001\n\013ListInd" +
      "exes\022-.google.firestore.admin.v1.ListInd" +
      "exesRequest\032..google.firestore.admin.v1." +
      "ListIndexesResponse\"O\332A\006parent\202\323\344\223\002@\022>/v" +
      "1/{parent=projects/*/databases/*/collect" +
      "ionGroups/*}/indexes\022\247\001\n\010GetIndex\022*.goog" +
      "le.firestore.admin.v1.GetIndexRequest\032 ." +
      "google.firestore.admin.v1.Index\"M\332A\004name" +
      "\202\323\344\223\002@\022>/v1/{name=projects/*/databases/*" +
      "/collectionGroups/*/indexes/*}\022\243\001\n\013Delet" +
      "eIndex\022-.google.firestore.admin.v1.Delet" +
      "eIndexRequest\032\026.google.protobuf.Empty\"M\332" +
      "A\004name\202\323\344\223\002@*>/v1/{name=projects/*/datab" +
      "ases/*/collectionGroups/*/indexes/*}\022\246\001\n" +
      "\010GetField\022*.google.firestore.admin.v1.Ge" +
      "tFieldRequest\032 .google.firestore.admin.v" +
      "1.Field\"L\332A\004name\202\323\344\223\002?\022=/v1/{name=projec" +
      "ts/*/databases/*/collectionGroups/*/fiel" +
      "ds/*}\022\331\001\n\013UpdateField\022-.google.firestore" +
      ".admin.v1.UpdateFieldRequest\032\035.google.lo" +
      "ngrunning.Operation\"|\312A\037\n\005Field\022\026FieldOp" +
      "erationMetadata\332A\005field\202\323\344\223\002L2C/v1/{fiel" +
      "d.name=projects/*/databases/*/collection" +
      "Groups/*/fields/*}:\005field\022\271\001\n\nListFields" +
      "\022,.google.firestore.admin.v1.ListFieldsR" +
      "equest\032-.google.firestore.admin.v1.ListF" +
      "ieldsResponse\"N\332A\006parent\202\323\344\223\002?\022=/v1/{par" +
      "ent=projects/*/databases/*/collectionGro" +
      "ups/*}/fields\022\335\001\n\017ExportDocuments\0221.goog" +
      "le.firestore.admin.v1.ExportDocumentsReq" +
      "uest\032\035.google.longrunning.Operation\"x\312A2" +
      "\n\027ExportDocumentsResponse\022\027ExportDocumen" +
      "tsMetadata\332A\004name\202\323\344\223\0026\"1/v1/{name=proje" +
      "cts/*/databases/*}:exportDocuments:\001*\022\333\001" +
      "\n\017ImportDocuments\0221.google.firestore.adm" +
      "in.v1.ImportDocumentsRequest\032\035.google.lo" +
      "ngrunning.Operation\"v\312A0\n\025google.protobu" +
      "f.Empty\022\027ImportDocumentsMetadata\332A\004name\202" +
      "\323\344\223\0026\"1/v1/{name=projects/*/databases/*}" +
      ":importDocuments:\001*\022\331\001\n\016CreateDatabase\0220" +
      ".google.firestore.admin.v1.CreateDatabas" +
      "eRequest\032\035.google.longrunning.Operation\"" +
      "v\312A\"\n\010Database\022\026CreateDatabaseMetadata\332A" +
      "\033parent,database,database_id\202\323\344\223\002-\"!/v1/" +
      "{parent=projects/*}/databases:\010database\022" +
      "\223\001\n\013GetDatabase\022-.google.firestore.admin" +
      ".v1.GetDatabaseRequest\032#.google.firestor" +
      "e.admin.v1.Database\"0\332A\004name\202\323\344\223\002#\022!/v1/" +
      "{name=projects/*/databases/*}\022\246\001\n\rListDa" +
      "tabases\022/.google.firestore.admin.v1.List" +
      "DatabasesRequest\0320.google.firestore.admi" +
      "n.v1.ListDatabasesResponse\"2\332A\006parent\202\323\344" +
      "\223\002#\022!/v1/{parent=projects/*}/databases\022\333" +
      "\001\n\016UpdateDatabase\0220.google.firestore.adm" +
      "in.v1.UpdateDatabaseRequest\032\035.google.lon" +
      "grunning.Operation\"x\312A\"\n\010Database\022\026Updat" +
      "eDatabaseMetadata\332A\024database,update_mask" +
      "\202\323\344\223\00262*/v1/{database.name=projects/*/da" +
      "tabases/*}:\010database\022\270\001\n\016DeleteDatabase\022" +
      "0.google.firestore.admin.v1.DeleteDataba" +
      "seRequest\032\035.google.longrunning.Operation" +
      "\"U\312A\"\n\010Database\022\026DeleteDatabaseMetadata\332" +
      "A\004name\202\323\344\223\002#*!/v1/{name=projects/*/datab" +
      "ases/*}\032v\312A\030firestore.googleapis.com\322AXh" +
      "ttps://www.googleapis.com/auth/cloud-pla" +
      "tform,https://www.googleapis.com/auth/da" +
      "tastoreB\245\003\n\035com.google.firestore.admin.v" +
      "1B\023FirestoreAdminProtoP\001Z9cloud.google.c" +
      "om/go/firestore/apiv1/admin/adminpb;admi" +
      "npb\242\002\004GCFS\252\002\037Google.Cloud.Firestore.Admi" +
      "n.V1\312\002\037Google\\Cloud\\Firestore\\Admin\\V1\352\002" +
      "#Google::Cloud::Firestore::Admin::V1\352AL\n" +
      "!firestore.googleapis.com/Location\022\'proj" +
      "ects/{project}/locations/{location}\352Aq\n(" +
      "firestore.googleapis.com/CollectionGroup" +
      "\022Eprojects/{project}/databases/{database" +
      "}/collectionGroups/{collection}b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.api.ClientProto.getDescriptor(),
          com.google.api.FieldBehaviorProto.getDescriptor(),
          com.google.api.ResourceProto.getDescriptor(),
          com.google.firestore.admin.v1.DatabaseProto.getDescriptor(),
          com.google.firestore.admin.v1.FieldProto.getDescriptor(),
          com.google.firestore.admin.v1.IndexProto.getDescriptor(),
          com.google.firestore.admin.v1.OperationProto.getDescriptor(),
          com.google.longrunning.OperationsProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.FieldMaskProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_google_firestore_admin_v1_ListDatabasesRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_firestore_admin_v1_ListDatabasesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_firestore_admin_v1_ListDatabasesRequest_descriptor,
        new java.lang.String[] { "Parent", });
    internal_static_google_firestore_admin_v1_CreateDatabaseRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_firestore_admin_v1_CreateDatabaseRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_firestore_admin_v1_CreateDatabaseRequest_descriptor,
        new java.lang.String[] { "Parent", "Database", "DatabaseId", });
    internal_static_google_firestore_admin_v1_CreateDatabaseMetadata_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_firestore_admin_v1_CreateDatabaseMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_firestore_admin_v1_CreateDatabaseMetadata_descriptor,
        new java.lang.String[] { });
    internal_static_google_firestore_admin_v1_ListDatabasesResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_google_firestore_admin_v1_ListDatabasesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_firestore_admin_v1_ListDatabasesResponse_descriptor,
        new java.lang.String[] { "Databases", "Unreachable", });
    internal_static_google_firestore_admin_v1_GetDatabaseRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_google_firestore_admin_v1_GetDatabaseRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_firestore_admin_v1_GetDatabaseRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_google_firestore_admin_v1_UpdateDatabaseRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_google_firestore_admin_v1_UpdateDatabaseRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_firestore_admin_v1_UpdateDatabaseRequest_descriptor,
        new java.lang.String[] { "Database", "UpdateMask", });
    internal_static_google_firestore_admin_v1_UpdateDatabaseMetadata_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_google_firestore_admin_v1_UpdateDatabaseMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_firestore_admin_v1_UpdateDatabaseMetadata_descriptor,
        new java.lang.String[] { });
    internal_static_google_firestore_admin_v1_DeleteDatabaseRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_google_firestore_admin_v1_DeleteDatabaseRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_firestore_admin_v1_DeleteDatabaseRequest_descriptor,
        new java.lang.String[] { "Name", "Etag", });
    internal_static_google_firestore_admin_v1_DeleteDatabaseMetadata_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_google_firestore_admin_v1_DeleteDatabaseMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_firestore_admin_v1_DeleteDatabaseMetadata_descriptor,
        new java.lang.String[] { });
    internal_static_google_firestore_admin_v1_CreateIndexRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_google_firestore_admin_v1_CreateIndexRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_firestore_admin_v1_CreateIndexRequest_descriptor,
        new java.lang.String[] { "Parent", "Index", });
    internal_static_google_firestore_admin_v1_ListIndexesRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_google_firestore_admin_v1_ListIndexesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_firestore_admin_v1_ListIndexesRequest_descriptor,
        new java.lang.String[] { "Parent", "Filter", "PageSize", "PageToken", });
    internal_static_google_firestore_admin_v1_ListIndexesResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_google_firestore_admin_v1_ListIndexesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_firestore_admin_v1_ListIndexesResponse_descriptor,
        new java.lang.String[] { "Indexes", "NextPageToken", });
    internal_static_google_firestore_admin_v1_GetIndexRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_google_firestore_admin_v1_GetIndexRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_firestore_admin_v1_GetIndexRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_google_firestore_admin_v1_DeleteIndexRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_google_firestore_admin_v1_DeleteIndexRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_firestore_admin_v1_DeleteIndexRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_google_firestore_admin_v1_UpdateFieldRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_google_firestore_admin_v1_UpdateFieldRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_firestore_admin_v1_UpdateFieldRequest_descriptor,
        new java.lang.String[] { "Field", "UpdateMask", });
    internal_static_google_firestore_admin_v1_GetFieldRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_google_firestore_admin_v1_GetFieldRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_firestore_admin_v1_GetFieldRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_google_firestore_admin_v1_ListFieldsRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_google_firestore_admin_v1_ListFieldsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_firestore_admin_v1_ListFieldsRequest_descriptor,
        new java.lang.String[] { "Parent", "Filter", "PageSize", "PageToken", });
    internal_static_google_firestore_admin_v1_ListFieldsResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_google_firestore_admin_v1_ListFieldsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_firestore_admin_v1_ListFieldsResponse_descriptor,
        new java.lang.String[] { "Fields", "NextPageToken", });
    internal_static_google_firestore_admin_v1_ExportDocumentsRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_google_firestore_admin_v1_ExportDocumentsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_firestore_admin_v1_ExportDocumentsRequest_descriptor,
        new java.lang.String[] { "Name", "CollectionIds", "OutputUriPrefix", "NamespaceIds", "SnapshotTime", });
    internal_static_google_firestore_admin_v1_ImportDocumentsRequest_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_google_firestore_admin_v1_ImportDocumentsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_firestore_admin_v1_ImportDocumentsRequest_descriptor,
        new java.lang.String[] { "Name", "CollectionIds", "InputUriPrefix", "NamespaceIds", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.ClientProto.defaultHost);
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.google.api.ClientProto.methodSignature);
    registry.add(com.google.api.ClientProto.oauthScopes);
    registry.add(com.google.api.ResourceProto.resourceDefinition);
    registry.add(com.google.api.ResourceProto.resourceReference);
    registry.add(com.google.longrunning.OperationsProto.operationInfo);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.ClientProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.firestore.admin.v1.DatabaseProto.getDescriptor();
    com.google.firestore.admin.v1.FieldProto.getDescriptor();
    com.google.firestore.admin.v1.IndexProto.getDescriptor();
    com.google.firestore.admin.v1.OperationProto.getDescriptor();
    com.google.longrunning.OperationsProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.FieldMaskProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
