// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/firestore/admin/v1/firestore_admin.proto

package com.google.firestore.admin.v1;

public interface ListDatabasesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.firestore.admin.v1.ListDatabasesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The databases in the project.
   * </pre>
   *
   * <code>repeated .google.firestore.admin.v1.Database databases = 1;</code>
   */
  java.util.List<com.google.firestore.admin.v1.Database> 
      getDatabasesList();
  /**
   * <pre>
   * The databases in the project.
   * </pre>
   *
   * <code>repeated .google.firestore.admin.v1.Database databases = 1;</code>
   */
  com.google.firestore.admin.v1.Database getDatabases(int index);
  /**
   * <pre>
   * The databases in the project.
   * </pre>
   *
   * <code>repeated .google.firestore.admin.v1.Database databases = 1;</code>
   */
  int getDatabasesCount();
  /**
   * <pre>
   * The databases in the project.
   * </pre>
   *
   * <code>repeated .google.firestore.admin.v1.Database databases = 1;</code>
   */
  java.util.List<? extends com.google.firestore.admin.v1.DatabaseOrBuilder> 
      getDatabasesOrBuilderList();
  /**
   * <pre>
   * The databases in the project.
   * </pre>
   *
   * <code>repeated .google.firestore.admin.v1.Database databases = 1;</code>
   */
  com.google.firestore.admin.v1.DatabaseOrBuilder getDatabasesOrBuilder(
      int index);
}
