// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/firestore/admin/v1/firestore_admin.proto

// Protobuf Java Version: 3.25.3
package com.google.firestore.admin.v1;

public interface ListBackupsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.firestore.admin.v1.ListBackupsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required. The location to list backups from.
   *
   * Format is `projects/{project}/locations/{location}`.
   * Use `{location} = '-'` to list backups from all locations for the given
   * project. This allows listing backups from a single location or from all
   * locations.
   * </pre>
   *
   * <code>string parent = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
   * @return The parent.
   */
  java.lang.String getParent();
  /**
   * <pre>
   * Required. The location to list backups from.
   *
   * Format is `projects/{project}/locations/{location}`.
   * Use `{location} = '-'` to list backups from all locations for the given
   * project. This allows listing backups from a single location or from all
   * locations.
   * </pre>
   *
   * <code>string parent = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
   * @return The bytes for parent.
   */
  com.google.protobuf.ByteString
      getParentBytes();
}
