// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/firestore/admin/v1/firestore_admin.proto

package com.google.firestore.admin.v1;

/**
 * <pre>
 * The list of databases for a project.
 * </pre>
 *
 * Protobuf type {@code google.firestore.admin.v1.ListDatabasesResponse}
 */
public final class ListDatabasesResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.firestore.admin.v1.ListDatabasesResponse)
    ListDatabasesResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListDatabasesResponse.newBuilder() to construct.
  private ListDatabasesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListDatabasesResponse() {
    databases_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListDatabasesResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ListDatabasesResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              databases_ = new java.util.ArrayList<com.google.firestore.admin.v1.Database>();
              mutable_bitField0_ |= 0x00000001;
            }
            databases_.add(
                input.readMessage(com.google.firestore.admin.v1.Database.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        databases_ = java.util.Collections.unmodifiableList(databases_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.firestore.admin.v1.FirestoreAdminProto.internal_static_google_firestore_admin_v1_ListDatabasesResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.firestore.admin.v1.FirestoreAdminProto.internal_static_google_firestore_admin_v1_ListDatabasesResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.firestore.admin.v1.ListDatabasesResponse.class, com.google.firestore.admin.v1.ListDatabasesResponse.Builder.class);
  }

  public static final int DATABASES_FIELD_NUMBER = 1;
  private java.util.List<com.google.firestore.admin.v1.Database> databases_;
  /**
   * <pre>
   * The databases in the project.
   * </pre>
   *
   * <code>repeated .google.firestore.admin.v1.Database databases = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.google.firestore.admin.v1.Database> getDatabasesList() {
    return databases_;
  }
  /**
   * <pre>
   * The databases in the project.
   * </pre>
   *
   * <code>repeated .google.firestore.admin.v1.Database databases = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.firestore.admin.v1.DatabaseOrBuilder> 
      getDatabasesOrBuilderList() {
    return databases_;
  }
  /**
   * <pre>
   * The databases in the project.
   * </pre>
   *
   * <code>repeated .google.firestore.admin.v1.Database databases = 1;</code>
   */
  @java.lang.Override
  public int getDatabasesCount() {
    return databases_.size();
  }
  /**
   * <pre>
   * The databases in the project.
   * </pre>
   *
   * <code>repeated .google.firestore.admin.v1.Database databases = 1;</code>
   */
  @java.lang.Override
  public com.google.firestore.admin.v1.Database getDatabases(int index) {
    return databases_.get(index);
  }
  /**
   * <pre>
   * The databases in the project.
   * </pre>
   *
   * <code>repeated .google.firestore.admin.v1.Database databases = 1;</code>
   */
  @java.lang.Override
  public com.google.firestore.admin.v1.DatabaseOrBuilder getDatabasesOrBuilder(
      int index) {
    return databases_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < databases_.size(); i++) {
      output.writeMessage(1, databases_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < databases_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, databases_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.firestore.admin.v1.ListDatabasesResponse)) {
      return super.equals(obj);
    }
    com.google.firestore.admin.v1.ListDatabasesResponse other = (com.google.firestore.admin.v1.ListDatabasesResponse) obj;

    if (!getDatabasesList()
        .equals(other.getDatabasesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getDatabasesCount() > 0) {
      hash = (37 * hash) + DATABASES_FIELD_NUMBER;
      hash = (53 * hash) + getDatabasesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.firestore.admin.v1.ListDatabasesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.firestore.admin.v1.ListDatabasesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.firestore.admin.v1.ListDatabasesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.firestore.admin.v1.ListDatabasesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.firestore.admin.v1.ListDatabasesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.firestore.admin.v1.ListDatabasesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.firestore.admin.v1.ListDatabasesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.firestore.admin.v1.ListDatabasesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.firestore.admin.v1.ListDatabasesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.firestore.admin.v1.ListDatabasesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.firestore.admin.v1.ListDatabasesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.firestore.admin.v1.ListDatabasesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.firestore.admin.v1.ListDatabasesResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The list of databases for a project.
   * </pre>
   *
   * Protobuf type {@code google.firestore.admin.v1.ListDatabasesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.firestore.admin.v1.ListDatabasesResponse)
      com.google.firestore.admin.v1.ListDatabasesResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.firestore.admin.v1.FirestoreAdminProto.internal_static_google_firestore_admin_v1_ListDatabasesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.firestore.admin.v1.FirestoreAdminProto.internal_static_google_firestore_admin_v1_ListDatabasesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.firestore.admin.v1.ListDatabasesResponse.class, com.google.firestore.admin.v1.ListDatabasesResponse.Builder.class);
    }

    // Construct using com.google.firestore.admin.v1.ListDatabasesResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDatabasesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (databasesBuilder_ == null) {
        databases_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        databasesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.firestore.admin.v1.FirestoreAdminProto.internal_static_google_firestore_admin_v1_ListDatabasesResponse_descriptor;
    }

    @java.lang.Override
    public com.google.firestore.admin.v1.ListDatabasesResponse getDefaultInstanceForType() {
      return com.google.firestore.admin.v1.ListDatabasesResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.firestore.admin.v1.ListDatabasesResponse build() {
      com.google.firestore.admin.v1.ListDatabasesResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.firestore.admin.v1.ListDatabasesResponse buildPartial() {
      com.google.firestore.admin.v1.ListDatabasesResponse result = new com.google.firestore.admin.v1.ListDatabasesResponse(this);
      int from_bitField0_ = bitField0_;
      if (databasesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          databases_ = java.util.Collections.unmodifiableList(databases_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.databases_ = databases_;
      } else {
        result.databases_ = databasesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.firestore.admin.v1.ListDatabasesResponse) {
        return mergeFrom((com.google.firestore.admin.v1.ListDatabasesResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.firestore.admin.v1.ListDatabasesResponse other) {
      if (other == com.google.firestore.admin.v1.ListDatabasesResponse.getDefaultInstance()) return this;
      if (databasesBuilder_ == null) {
        if (!other.databases_.isEmpty()) {
          if (databases_.isEmpty()) {
            databases_ = other.databases_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDatabasesIsMutable();
            databases_.addAll(other.databases_);
          }
          onChanged();
        }
      } else {
        if (!other.databases_.isEmpty()) {
          if (databasesBuilder_.isEmpty()) {
            databasesBuilder_.dispose();
            databasesBuilder_ = null;
            databases_ = other.databases_;
            bitField0_ = (bitField0_ & ~0x00000001);
            databasesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDatabasesFieldBuilder() : null;
          } else {
            databasesBuilder_.addAllMessages(other.databases_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.firestore.admin.v1.ListDatabasesResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.firestore.admin.v1.ListDatabasesResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.google.firestore.admin.v1.Database> databases_ =
      java.util.Collections.emptyList();
    private void ensureDatabasesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        databases_ = new java.util.ArrayList<com.google.firestore.admin.v1.Database>(databases_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.firestore.admin.v1.Database, com.google.firestore.admin.v1.Database.Builder, com.google.firestore.admin.v1.DatabaseOrBuilder> databasesBuilder_;

    /**
     * <pre>
     * The databases in the project.
     * </pre>
     *
     * <code>repeated .google.firestore.admin.v1.Database databases = 1;</code>
     */
    public java.util.List<com.google.firestore.admin.v1.Database> getDatabasesList() {
      if (databasesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(databases_);
      } else {
        return databasesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * The databases in the project.
     * </pre>
     *
     * <code>repeated .google.firestore.admin.v1.Database databases = 1;</code>
     */
    public int getDatabasesCount() {
      if (databasesBuilder_ == null) {
        return databases_.size();
      } else {
        return databasesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * The databases in the project.
     * </pre>
     *
     * <code>repeated .google.firestore.admin.v1.Database databases = 1;</code>
     */
    public com.google.firestore.admin.v1.Database getDatabases(int index) {
      if (databasesBuilder_ == null) {
        return databases_.get(index);
      } else {
        return databasesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * The databases in the project.
     * </pre>
     *
     * <code>repeated .google.firestore.admin.v1.Database databases = 1;</code>
     */
    public Builder setDatabases(
        int index, com.google.firestore.admin.v1.Database value) {
      if (databasesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDatabasesIsMutable();
        databases_.set(index, value);
        onChanged();
      } else {
        databasesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The databases in the project.
     * </pre>
     *
     * <code>repeated .google.firestore.admin.v1.Database databases = 1;</code>
     */
    public Builder setDatabases(
        int index, com.google.firestore.admin.v1.Database.Builder builderForValue) {
      if (databasesBuilder_ == null) {
        ensureDatabasesIsMutable();
        databases_.set(index, builderForValue.build());
        onChanged();
      } else {
        databasesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The databases in the project.
     * </pre>
     *
     * <code>repeated .google.firestore.admin.v1.Database databases = 1;</code>
     */
    public Builder addDatabases(com.google.firestore.admin.v1.Database value) {
      if (databasesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDatabasesIsMutable();
        databases_.add(value);
        onChanged();
      } else {
        databasesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * The databases in the project.
     * </pre>
     *
     * <code>repeated .google.firestore.admin.v1.Database databases = 1;</code>
     */
    public Builder addDatabases(
        int index, com.google.firestore.admin.v1.Database value) {
      if (databasesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDatabasesIsMutable();
        databases_.add(index, value);
        onChanged();
      } else {
        databasesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The databases in the project.
     * </pre>
     *
     * <code>repeated .google.firestore.admin.v1.Database databases = 1;</code>
     */
    public Builder addDatabases(
        com.google.firestore.admin.v1.Database.Builder builderForValue) {
      if (databasesBuilder_ == null) {
        ensureDatabasesIsMutable();
        databases_.add(builderForValue.build());
        onChanged();
      } else {
        databasesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The databases in the project.
     * </pre>
     *
     * <code>repeated .google.firestore.admin.v1.Database databases = 1;</code>
     */
    public Builder addDatabases(
        int index, com.google.firestore.admin.v1.Database.Builder builderForValue) {
      if (databasesBuilder_ == null) {
        ensureDatabasesIsMutable();
        databases_.add(index, builderForValue.build());
        onChanged();
      } else {
        databasesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The databases in the project.
     * </pre>
     *
     * <code>repeated .google.firestore.admin.v1.Database databases = 1;</code>
     */
    public Builder addAllDatabases(
        java.lang.Iterable<? extends com.google.firestore.admin.v1.Database> values) {
      if (databasesBuilder_ == null) {
        ensureDatabasesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, databases_);
        onChanged();
      } else {
        databasesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * The databases in the project.
     * </pre>
     *
     * <code>repeated .google.firestore.admin.v1.Database databases = 1;</code>
     */
    public Builder clearDatabases() {
      if (databasesBuilder_ == null) {
        databases_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        databasesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The databases in the project.
     * </pre>
     *
     * <code>repeated .google.firestore.admin.v1.Database databases = 1;</code>
     */
    public Builder removeDatabases(int index) {
      if (databasesBuilder_ == null) {
        ensureDatabasesIsMutable();
        databases_.remove(index);
        onChanged();
      } else {
        databasesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * The databases in the project.
     * </pre>
     *
     * <code>repeated .google.firestore.admin.v1.Database databases = 1;</code>
     */
    public com.google.firestore.admin.v1.Database.Builder getDatabasesBuilder(
        int index) {
      return getDatabasesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * The databases in the project.
     * </pre>
     *
     * <code>repeated .google.firestore.admin.v1.Database databases = 1;</code>
     */
    public com.google.firestore.admin.v1.DatabaseOrBuilder getDatabasesOrBuilder(
        int index) {
      if (databasesBuilder_ == null) {
        return databases_.get(index);  } else {
        return databasesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * The databases in the project.
     * </pre>
     *
     * <code>repeated .google.firestore.admin.v1.Database databases = 1;</code>
     */
    public java.util.List<? extends com.google.firestore.admin.v1.DatabaseOrBuilder> 
         getDatabasesOrBuilderList() {
      if (databasesBuilder_ != null) {
        return databasesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(databases_);
      }
    }
    /**
     * <pre>
     * The databases in the project.
     * </pre>
     *
     * <code>repeated .google.firestore.admin.v1.Database databases = 1;</code>
     */
    public com.google.firestore.admin.v1.Database.Builder addDatabasesBuilder() {
      return getDatabasesFieldBuilder().addBuilder(
          com.google.firestore.admin.v1.Database.getDefaultInstance());
    }
    /**
     * <pre>
     * The databases in the project.
     * </pre>
     *
     * <code>repeated .google.firestore.admin.v1.Database databases = 1;</code>
     */
    public com.google.firestore.admin.v1.Database.Builder addDatabasesBuilder(
        int index) {
      return getDatabasesFieldBuilder().addBuilder(
          index, com.google.firestore.admin.v1.Database.getDefaultInstance());
    }
    /**
     * <pre>
     * The databases in the project.
     * </pre>
     *
     * <code>repeated .google.firestore.admin.v1.Database databases = 1;</code>
     */
    public java.util.List<com.google.firestore.admin.v1.Database.Builder> 
         getDatabasesBuilderList() {
      return getDatabasesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.firestore.admin.v1.Database, com.google.firestore.admin.v1.Database.Builder, com.google.firestore.admin.v1.DatabaseOrBuilder> 
        getDatabasesFieldBuilder() {
      if (databasesBuilder_ == null) {
        databasesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.firestore.admin.v1.Database, com.google.firestore.admin.v1.Database.Builder, com.google.firestore.admin.v1.DatabaseOrBuilder>(
                databases_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        databases_ = null;
      }
      return databasesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.firestore.admin.v1.ListDatabasesResponse)
  }

  // @@protoc_insertion_point(class_scope:google.firestore.admin.v1.ListDatabasesResponse)
  private static final com.google.firestore.admin.v1.ListDatabasesResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.firestore.admin.v1.ListDatabasesResponse();
  }

  public static com.google.firestore.admin.v1.ListDatabasesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListDatabasesResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListDatabasesResponse>() {
    @java.lang.Override
    public ListDatabasesResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ListDatabasesResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ListDatabasesResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListDatabasesResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.firestore.admin.v1.ListDatabasesResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

