// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/firestore/admin/v1/location.proto

package com.google.firestore.admin.v1;

public final class LocationProto {
  private LocationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_firestore_admin_v1_LocationMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_admin_v1_LocationMetadata_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(google/firestore/admin/v1/location.pro" +
      "to\022\031google.firestore.admin.v1\"\022\n\020Locatio" +
      "nMetadataB\341\001\n\035com.google.firestore.admin" +
      ".v1B\rLocationProtoP\001Z>google.golang.org/" +
      "genproto/googleapis/firestore/admin/v1;a" +
      "dmin\242\002\004GCFS\252\002\037Google.Cloud.Firestore.Adm" +
      "in.V1\312\002\037Google\\Cloud\\Firestore\\Admin\\V1\352" +
      "\002#Google::Cloud::Firestore::Admin::V1b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_google_firestore_admin_v1_LocationMetadata_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_firestore_admin_v1_LocationMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_firestore_admin_v1_LocationMetadata_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
