# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""This script is used to synthesize generated parts of this library."""

import synthtool as s
import synthtool.gcp as gcp
import synthtool.languages.java as java

gapic = gcp.GAPICGenerator()

protobuf_header = "// Generated by the protocol buffer compiler.  DO NOT EDIT!"
# License header
license_header = """/*
 * Copyright 2019 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
"""
bad_license_header = """/\\*
 \\* Copyright 2018 Google LLC
 \\*
 \\* Licensed under the Apache License, Version 2.0 \\(the "License"\\); you may not use this file except
 \\* in compliance with the License. You may obtain a copy of the License at
 \\*
 \\* http://www.apache.org/licenses/LICENSE-2.0
 \\*
 \\* Unless required by applicable law or agreed to in writing, software distributed under the License
 \\* is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 \\* or implied. See the License for the specific language governing permissions and limitations under
 \\* the License.
 \\*/
"""


def generate_client(service, version, config_path):
  library = gapic.java_library(
      service=service,
      version=version,
      config_path=config_path,
      artman_output_name='')

  s.replace(
      library / f'proto-google-cloud-{service}-{version}/src/**/*.java',
      protobuf_header,
      f'{license_header}{protobuf_header}'
  )
  s.replace(
      library / f'grpc-google-cloud-{service}-{version}/src/**/*.java',
      bad_license_header,
      license_header
  )
  s.replace(
      library / f'proto-google-cloud-{service}-{version}/src/**/*.java',
      bad_license_header,
      license_header
  )
  java.format_code(f'grpc-google-cloud-{service}-{version}/src')
  java.format_code(f'proto-google-cloud-{service}-{version}/src')

  return library

admin_v1 = generate_client('firestore-admin', 'v1', '/google/firestore/admin/artman_firestore_v1.yaml')
s.replace(
    admin_v1 / f'grpc-google-cloud-firestore-admin-v1/src/**/*.java',
    'package com.google.firestore.admin.v1;',
    f'{license_header}package com.google.firestore.admin.v1;'
)
s.copy(admin_v1 / 'gapic-google-cloud-firestore-admin-v1/src', 'google-cloud-firestore/src')
s.copy(admin_v1 / 'grpc-google-cloud-firestore-admin-v1/src', 'grpc-google-cloud-firestore-admin-v1/src')
s.copy(admin_v1 / 'proto-google-cloud-firestore-admin-v1/src', 'proto-google-cloud-firestore-admin-v1/src')

firestore_v1 = generate_client('firestore', 'v1',      '/google/firestore/artman_firestore_v1.yaml')
s.replace(
    firestore_v1 / f'grpc-google-cloud-firestore-v1/src/**/*.java',
    'package com.google.firestore.v1;',
    f'{license_header}package com.google.firestore.v1;'
)
s.copy(firestore_v1 / 'grpc-google-cloud-firestore-v1/src', 'grpc-google-cloud-firestore-v1/src')
s.copy(firestore_v1 / 'proto-google-cloud-firestore-v1/src', 'proto-google-cloud-firestore-v1/src')

firestore_v1beta1 = generate_client('firestore', 'v1beta1', '/google/firestore/artman_firestore.yaml')
s.replace(
    firestore_v1beta1 / f'grpc-google-cloud-firestore-v1beta1/src/**/*.java',
    'package com.google.firestore.v1beta1;',
    f'{license_header}package com.google.firestore.v1beta1;'
)
s.copy(firestore_v1beta1 / 'grpc-google-cloud-firestore-v1beta1/src', 'grpc-google-cloud-firestore-v1beta1/src')
s.copy(firestore_v1beta1 / 'proto-google-cloud-firestore-v1beta1/src', 'proto-google-cloud-firestore-v1beta1/src')

common_templates = gcp.CommonTemplates()
templates = common_templates.java_library()
s.copy(templates, excludes=[
    '.gitignore',
    'README.md',
    # firestore uses a different project for its integration tests
    # due to the default project running datastore
    '.kokoro/presubmit/integration.cfg'
])
