/*
 * Copyright 2019 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/firestore/admin/v1/firestore_admin.proto

package com.google.firestore.admin.v1;

public interface CreateIndexRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.firestore.admin.v1.CreateIndexRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A parent name of the form
   * `projects/{project_id}/databases/{database_id}/collectionGroups/{collection_id}`
   * </pre>
   *
   * <code>string parent = 1;</code>
   */
  java.lang.String getParent();
  /**
   * <pre>
   * A parent name of the form
   * `projects/{project_id}/databases/{database_id}/collectionGroups/{collection_id}`
   * </pre>
   *
   * <code>string parent = 1;</code>
   */
  com.google.protobuf.ByteString
      getParentBytes();

  /**
   * <pre>
   * The composite index to create.
   * </pre>
   *
   * <code>.google.firestore.admin.v1.Index index = 2;</code>
   */
  boolean hasIndex();
  /**
   * <pre>
   * The composite index to create.
   * </pre>
   *
   * <code>.google.firestore.admin.v1.Index index = 2;</code>
   */
  com.google.firestore.admin.v1.Index getIndex();
  /**
   * <pre>
   * The composite index to create.
   * </pre>
   *
   * <code>.google.firestore.admin.v1.Index index = 2;</code>
   */
  com.google.firestore.admin.v1.IndexOrBuilder getIndexOrBuilder();
}
