// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/firestore/v1/bloom_filter.proto
// Protobuf Java Version: 4.33.0

package com.google.firestore.v1;

@com.google.protobuf.Generated
public interface BitSequenceOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.firestore.v1.BitSequence)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * The bytes that encode the bit sequence.
   * May have a length of zero.
   * </pre>
   *
   * <code>bytes bitmap = 1;</code>
   *
   * @return The bitmap.
   */
  com.google.protobuf.ByteString getBitmap();

  /**
   *
   *
   * <pre>
   * The number of bits of the last byte in `bitmap` to ignore as "padding".
   * If the length of `bitmap` is zero, then this value must be `0`.
   * Otherwise, this value must be between 0 and 7, inclusive.
   * </pre>
   *
   * <code>int32 padding = 2;</code>
   *
   * @return The padding.
   */
  int getPadding();
}
