// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/firestore/v1/bloom_filter.proto
// Protobuf Java Version: 4.33.0

package com.google.firestore.v1;

@com.google.protobuf.Generated
public interface BloomFilterOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.firestore.v1.BloomFilter)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * The bloom filter data.
   * </pre>
   *
   * <code>.google.firestore.v1.BitSequence bits = 1;</code>
   *
   * @return Whether the bits field is set.
   */
  boolean hasBits();

  /**
   *
   *
   * <pre>
   * The bloom filter data.
   * </pre>
   *
   * <code>.google.firestore.v1.BitSequence bits = 1;</code>
   *
   * @return The bits.
   */
  com.google.firestore.v1.BitSequence getBits();

  /**
   *
   *
   * <pre>
   * The bloom filter data.
   * </pre>
   *
   * <code>.google.firestore.v1.BitSequence bits = 1;</code>
   */
  com.google.firestore.v1.BitSequenceOrBuilder getBitsOrBuilder();

  /**
   *
   *
   * <pre>
   * The number of hashes used by the algorithm.
   * </pre>
   *
   * <code>int32 hash_count = 2;</code>
   *
   * @return The hashCount.
   */
  int getHashCount();
}
