// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/firestore/v1/query_profile.proto
// Protobuf Java Version: 4.33.0

package com.google.firestore.v1;

@com.google.protobuf.Generated
public interface ExplainOptionsOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.firestore.v1.ExplainOptions)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Optional. Whether to execute this query.
   *
   * When false (the default), the query will be planned, returning only
   * metrics from the planning stages.
   *
   * When true, the query will be planned and executed, returning the full
   * query results along with both planning and execution stage metrics.
   * </pre>
   *
   * <code>bool analyze = 1 [(.google.api.field_behavior) = OPTIONAL];</code>
   *
   * @return The analyze.
   */
  boolean getAnalyze();
}
