/*
 * Copyright 2019 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/firestore/v1/firestore.proto

package com.google.firestore.v1;

public final class FirestoreProto {
  private FirestoreProto() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_firestore_v1_GetDocumentRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_v1_GetDocumentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_firestore_v1_ListDocumentsRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_v1_ListDocumentsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_firestore_v1_ListDocumentsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_v1_ListDocumentsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_firestore_v1_CreateDocumentRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_v1_CreateDocumentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_firestore_v1_UpdateDocumentRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_v1_UpdateDocumentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_firestore_v1_DeleteDocumentRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_v1_DeleteDocumentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_firestore_v1_BatchGetDocumentsRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_v1_BatchGetDocumentsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_firestore_v1_BatchGetDocumentsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_v1_BatchGetDocumentsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_firestore_v1_BeginTransactionRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_v1_BeginTransactionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_firestore_v1_BeginTransactionResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_v1_BeginTransactionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_firestore_v1_CommitRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_v1_CommitRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_firestore_v1_CommitResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_v1_CommitResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_firestore_v1_RollbackRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_v1_RollbackRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_firestore_v1_RunQueryRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_v1_RunQueryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_firestore_v1_RunQueryResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_v1_RunQueryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_firestore_v1_WriteRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_v1_WriteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_firestore_v1_WriteRequest_LabelsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_v1_WriteRequest_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_firestore_v1_WriteResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_v1_WriteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_firestore_v1_ListenRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_v1_ListenRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_firestore_v1_ListenRequest_LabelsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_v1_ListenRequest_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_firestore_v1_ListenResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_v1_ListenResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_firestore_v1_Target_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_v1_Target_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_firestore_v1_Target_DocumentsTarget_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_v1_Target_DocumentsTarget_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_firestore_v1_Target_QueryTarget_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_v1_Target_QueryTarget_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_firestore_v1_TargetChange_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_v1_TargetChange_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_firestore_v1_ListCollectionIdsRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_v1_ListCollectionIdsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_firestore_v1_ListCollectionIdsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_firestore_v1_ListCollectionIdsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n#google/firestore/v1/firestore.proto\022\023g"
          + "oogle.firestore.v1\032\034google/api/annotatio"
          + "ns.proto\032\027google/api/client.proto\032\037googl"
          + "e/api/field_behavior.proto\032 google/fires"
          + "tore/v1/common.proto\032\"google/firestore/v"
          + "1/document.proto\032\037google/firestore/v1/qu"
          + "ery.proto\032\037google/firestore/v1/write.pro"
          + "to\032\033google/protobuf/empty.proto\032\037google/"
          + "protobuf/timestamp.proto\032\027google/rpc/sta"
          + "tus.proto\"\270\001\n\022GetDocumentRequest\022\021\n\004name"
          + "\030\001 \001(\tB\003\340A\002\022/\n\004mask\030\002 \001(\0132!.google.fires"
          + "tore.v1.DocumentMask\022\025\n\013transaction\030\003 \001("
          + "\014H\000\022/\n\tread_time\030\005 \001(\0132\032.google.protobuf"
          + ".TimestampH\000B\026\n\024consistency_selector\"\247\002\n"
          + "\024ListDocumentsRequest\022\023\n\006parent\030\001 \001(\tB\003\340"
          + "A\002\022\032\n\rcollection_id\030\002 \001(\tB\003\340A\002\022\021\n\tpage_s"
          + "ize\030\003 \001(\005\022\022\n\npage_token\030\004 \001(\t\022\020\n\010order_b"
          + "y\030\006 \001(\t\022/\n\004mask\030\007 \001(\0132!.google.firestore"
          + ".v1.DocumentMask\022\025\n\013transaction\030\010 \001(\014H\000\022"
          + "/\n\tread_time\030\n \001(\0132\032.google.protobuf.Tim"
          + "estampH\000\022\024\n\014show_missing\030\014 \001(\010B\026\n\024consis"
          + "tency_selector\"b\n\025ListDocumentsResponse\022"
          + "0\n\tdocuments\030\001 \003(\0132\035.google.firestore.v1"
          + ".Document\022\027\n\017next_page_token\030\002 \001(\t\"\304\001\n\025C"
          + "reateDocumentRequest\022\023\n\006parent\030\001 \001(\tB\003\340A"
          + "\002\022\032\n\rcollection_id\030\002 \001(\tB\003\340A\002\022\023\n\013documen"
          + "t_id\030\003 \001(\t\0224\n\010document\030\004 \001(\0132\035.google.fi"
          + "restore.v1.DocumentB\003\340A\002\022/\n\004mask\030\005 \001(\0132!"
          + ".google.firestore.v1.DocumentMask\"\363\001\n\025Up"
          + "dateDocumentRequest\0224\n\010document\030\001 \001(\0132\035."
          + "google.firestore.v1.DocumentB\003\340A\002\0226\n\013upd"
          + "ate_mask\030\002 \001(\0132!.google.firestore.v1.Doc"
          + "umentMask\022/\n\004mask\030\003 \001(\0132!.google.firesto"
          + "re.v1.DocumentMask\022;\n\020current_document\030\004"
          + " \001(\0132!.google.firestore.v1.Precondition\""
          + "g\n\025DeleteDocumentRequest\022\021\n\004name\030\001 \001(\tB\003"
          + "\340A\002\022;\n\020current_document\030\002 \001(\0132!.google.f"
          + "irestore.v1.Precondition\"\231\002\n\030BatchGetDoc"
          + "umentsRequest\022\025\n\010database\030\001 \001(\tB\003\340A\002\022\021\n\t"
          + "documents\030\002 \003(\t\022/\n\004mask\030\003 \001(\0132!.google.f"
          + "irestore.v1.DocumentMask\022\025\n\013transaction\030"
          + "\004 \001(\014H\000\022B\n\017new_transaction\030\005 \001(\0132\'.googl"
          + "e.firestore.v1.TransactionOptionsH\000\022/\n\tr"
          + "ead_time\030\007 \001(\0132\032.google.protobuf.Timesta"
          + "mpH\000B\026\n\024consistency_selector\"\254\001\n\031BatchGe"
          + "tDocumentsResponse\022.\n\005found\030\001 \001(\0132\035.goog"
          + "le.firestore.v1.DocumentH\000\022\021\n\007missing\030\002 "
          + "\001(\tH\000\022\023\n\013transaction\030\003 \001(\014\022-\n\tread_time\030"
          + "\004 \001(\0132\032.google.protobuf.TimestampB\010\n\006res"
          + "ult\"j\n\027BeginTransactionRequest\022\025\n\010databa"
          + "se\030\001 \001(\tB\003\340A\002\0228\n\007options\030\002 \001(\0132\'.google."
          + "firestore.v1.TransactionOptions\"/\n\030Begin"
          + "TransactionResponse\022\023\n\013transaction\030\001 \001(\014"
          + "\"g\n\rCommitRequest\022\025\n\010database\030\001 \001(\tB\003\340A\002"
          + "\022*\n\006writes\030\002 \003(\0132\032.google.firestore.v1.W"
          + "rite\022\023\n\013transaction\030\003 \001(\014\"z\n\016CommitRespo"
          + "nse\0227\n\rwrite_results\030\001 \003(\0132 .google.fire"
          + "store.v1.WriteResult\022/\n\013commit_time\030\002 \001("
          + "\0132\032.google.protobuf.Timestamp\"B\n\017Rollbac"
          + "kRequest\022\025\n\010database\030\001 \001(\tB\003\340A\002\022\030\n\013trans"
          + "action\030\002 \001(\014B\003\340A\002\"\232\002\n\017RunQueryRequest\022\023\n"
          + "\006parent\030\001 \001(\tB\003\340A\002\022@\n\020structured_query\030\002"
          + " \001(\0132$.google.firestore.v1.StructuredQue"
          + "ryH\000\022\025\n\013transaction\030\005 \001(\014H\001\022B\n\017new_trans"
          + "action\030\006 \001(\0132\'.google.firestore.v1.Trans"
          + "actionOptionsH\001\022/\n\tread_time\030\007 \001(\0132\032.goo"
          + "gle.protobuf.TimestampH\001B\014\n\nquery_typeB\026"
          + "\n\024consistency_selector\"\240\001\n\020RunQueryRespo"
          + "nse\022\023\n\013transaction\030\002 \001(\014\022/\n\010document\030\001 \001"
          + "(\0132\035.google.firestore.v1.Document\022-\n\trea"
          + "d_time\030\003 \001(\0132\032.google.protobuf.Timestamp"
          + "\022\027\n\017skipped_results\030\004 \001(\005\"\350\001\n\014WriteReque"
          + "st\022\025\n\010database\030\001 \001(\tB\003\340A\002\022\021\n\tstream_id\030\002"
          + " \001(\t\022*\n\006writes\030\003 \003(\0132\032.google.firestore."
          + "v1.Write\022\024\n\014stream_token\030\004 \001(\014\022=\n\006labels"
          + "\030\005 \003(\0132-.google.firestore.v1.WriteReques"
          + "t.LabelsEntry\032-\n\013LabelsEntry\022\013\n\003key\030\001 \001("
          + "\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\242\001\n\rWriteResponse\022\021"
          + "\n\tstream_id\030\001 \001(\t\022\024\n\014stream_token\030\002 \001(\014\022"
          + "7\n\rwrite_results\030\003 \003(\0132 .google.firestor"
          + "e.v1.WriteResult\022/\n\013commit_time\030\004 \001(\0132\032."
          + "google.protobuf.Timestamp\"\362\001\n\rListenRequ"
          + "est\022\025\n\010database\030\001 \001(\tB\003\340A\002\0221\n\nadd_target"
          + "\030\002 \001(\0132\033.google.firestore.v1.TargetH\000\022\027\n"
          + "\rremove_target\030\003 \001(\005H\000\022>\n\006labels\030\004 \003(\0132."
          + ".google.firestore.v1.ListenRequest.Label"
          + "sEntry\032-\n\013LabelsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005va"
          + "lue\030\002 \001(\t:\0028\001B\017\n\rtarget_change\"\325\002\n\016Liste"
          + "nResponse\022:\n\rtarget_change\030\002 \001(\0132!.googl"
          + "e.firestore.v1.TargetChangeH\000\022>\n\017documen"
          + "t_change\030\003 \001(\0132#.google.firestore.v1.Doc"
          + "umentChangeH\000\022>\n\017document_delete\030\004 \001(\0132#"
          + ".google.firestore.v1.DocumentDeleteH\000\022>\n"
          + "\017document_remove\030\006 \001(\0132#.google.firestor"
          + "e.v1.DocumentRemoveH\000\0226\n\006filter\030\005 \001(\0132$."
          + "google.firestore.v1.ExistenceFilterH\000B\017\n"
          + "\rresponse_type\"\241\003\n\006Target\0228\n\005query\030\002 \001(\013"
          + "2\'.google.firestore.v1.Target.QueryTarge"
          + "tH\000\022@\n\tdocuments\030\003 \001(\0132+.google.firestor"
          + "e.v1.Target.DocumentsTargetH\000\022\026\n\014resume_"
          + "token\030\004 \001(\014H\001\022/\n\tread_time\030\013 \001(\0132\032.googl"
          + "e.protobuf.TimestampH\001\022\021\n\ttarget_id\030\005 \001("
          + "\005\022\014\n\004once\030\006 \001(\010\032$\n\017DocumentsTarget\022\021\n\tdo"
          + "cuments\030\002 \003(\t\032m\n\013QueryTarget\022\016\n\006parent\030\001"
          + " \001(\t\022@\n\020structured_query\030\002 \001(\0132$.google."
          + "firestore.v1.StructuredQueryH\000B\014\n\nquery_"
          + "typeB\r\n\013target_typeB\r\n\013resume_type\"\252\002\n\014T"
          + "argetChange\022N\n\022target_change_type\030\001 \001(\0162"
          + "2.google.firestore.v1.TargetChange.Targe"
          + "tChangeType\022\022\n\ntarget_ids\030\002 \003(\005\022!\n\005cause"
          + "\030\003 \001(\0132\022.google.rpc.Status\022\024\n\014resume_tok"
          + "en\030\004 \001(\014\022-\n\tread_time\030\006 \001(\0132\032.google.pro"
          + "tobuf.Timestamp\"N\n\020TargetChangeType\022\r\n\tN"
          + "O_CHANGE\020\000\022\007\n\003ADD\020\001\022\n\n\006REMOVE\020\002\022\013\n\007CURRE"
          + "NT\020\003\022\t\n\005RESET\020\004\"V\n\030ListCollectionIdsRequ"
          + "est\022\023\n\006parent\030\001 \001(\tB\003\340A\002\022\021\n\tpage_size\030\002 "
          + "\001(\005\022\022\n\npage_token\030\003 \001(\t\"L\n\031ListCollectio"
          + "nIdsResponse\022\026\n\016collection_ids\030\001 \003(\t\022\027\n\017"
          + "next_page_token\030\002 \001(\t2\327\023\n\tFirestore\022\217\001\n\013"
          + "GetDocument\022\'.google.firestore.v1.GetDoc"
          + "umentRequest\032\035.google.firestore.v1.Docum"
          + "ent\"8\202\323\344\223\0022\0220/v1/{name=projects/*/databa"
          + "ses/*/documents/*/**}\022\262\001\n\rListDocuments\022"
          + ").google.firestore.v1.ListDocumentsReque"
          + "st\032*.google.firestore.v1.ListDocumentsRe"
          + "sponse\"J\202\323\344\223\002D\022B/v1/{parent=projects/*/d"
          + "atabases/*/documents/*/**}/{collection_i"
          + "d}\022\257\001\n\016CreateDocument\022*.google.firestore"
          + ".v1.CreateDocumentRequest\032\035.google.fires"
          + "tore.v1.Document\"R\202\323\344\223\002L\"@/v1/{parent=pr"
          + "ojects/*/databases/*/documents/**}/{coll"
          + "ection_id}:\010document\022\277\001\n\016UpdateDocument\022"
          + "*.google.firestore.v1.UpdateDocumentRequ"
          + "est\032\035.google.firestore.v1.Document\"b\202\323\344\223"
          + "\002E29/v1/{document.name=projects/*/databa"
          + "ses/*/documents/*/**}:\010document\332A\024docume"
          + "nt,update_mask\022\225\001\n\016DeleteDocument\022*.goog"
          + "le.firestore.v1.DeleteDocumentRequest\032\026."
          + "google.protobuf.Empty\"?\202\323\344\223\0022*0/v1/{name"
          + "=projects/*/databases/*/documents/*/**}\332"
          + "A\004name\022\271\001\n\021BatchGetDocuments\022-.google.fi"
          + "restore.v1.BatchGetDocumentsRequest\032..go"
          + "ogle.firestore.v1.BatchGetDocumentsRespo"
          + "nse\"C\202\323\344\223\002=\"8/v1/{database=projects/*/da"
          + "tabases/*}/documents:batchGet:\001*0\001\022\307\001\n\020B"
          + "eginTransaction\022,.google.firestore.v1.Be"
          + "ginTransactionRequest\032-.google.firestore"
          + ".v1.BeginTransactionResponse\"V\202\323\344\223\002E\"@/v"
          + "1/{database=projects/*/databases/*}/docu"
          + "ments:beginTransaction:\001*\332A\010database\022\246\001\n"
          + "\006Commit\022\".google.firestore.v1.CommitRequ"
          + "est\032#.google.firestore.v1.CommitResponse"
          + "\"S\202\323\344\223\002;\"6/v1/{database=projects/*/datab"
          + "ases/*}/documents:commit:\001*\332A\017database,w"
          + "rites\022\244\001\n\010Rollback\022$.google.firestore.v1"
          + ".RollbackRequest\032\026.google.protobuf.Empty"
          + "\"Z\202\323\344\223\002=\"8/v1/{database=projects/*/datab"
          + "ases/*}/documents:rollback:\001*\332A\024database"
          + ",transaction\022\337\001\n\010RunQuery\022$.google.fires"
          + "tore.v1.RunQueryRequest\032%.google.firesto"
          + "re.v1.RunQueryResponse\"\203\001\202\323\344\223\002}\"6/v1/{pa"
          + "rent=projects/*/databases/*/documents}:r"
          + "unQuery:\001*Z@\";/v1/{parent=projects/*/dat"
          + "abases/*/documents/*/**}:runQuery:\001*0\001\022\224"
          + "\001\n\005Write\022!.google.firestore.v1.WriteRequ"
          + "est\032\".google.firestore.v1.WriteResponse\""
          + "@\202\323\344\223\002:\"5/v1/{database=projects/*/databa"
          + "ses/*}/documents:write:\001*(\0010\001\022\230\001\n\006Listen"
          + "\022\".google.firestore.v1.ListenRequest\032#.g"
          + "oogle.firestore.v1.ListenResponse\"A\202\323\344\223\002"
          + ";\"6/v1/{database=projects/*/databases/*}"
          + "/documents:listen:\001*(\0010\001\022\224\002\n\021ListCollect"
          + "ionIds\022-.google.firestore.v1.ListCollect"
          + "ionIdsRequest\032..google.firestore.v1.List"
          + "CollectionIdsResponse\"\237\001\202\323\344\223\002\217\001\"?/v1/{pa"
          + "rent=projects/*/databases/*/documents}:l"
          + "istCollectionIds:\001*ZI\"D/v1/{parent=proje"
          + "cts/*/databases/*/documents/*/**}:listCo"
          + "llectionIds:\001*\332A\006parent\032v\312A\030firestore.go"
          + "ogleapis.com\322AXhttps://www.googleapis.co"
          + "m/auth/cloud-platform,https://www.google"
          + "apis.com/auth/datastoreB\250\001\n\027com.google.f"
          + "irestore.v1B\016FirestoreProtoP\001Z<google.go"
          + "lang.org/genproto/googleapis/firestore/v"
          + "1;firestore\242\002\004GCFS\252\002\031Google.Cloud.Firest"
          + "ore.V1\312\002\031Google\\Cloud\\Firestore\\V1b\006prot"
          + "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
        descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.api.ClientProto.getDescriptor(),
          com.google.api.FieldBehaviorProto.getDescriptor(),
          com.google.firestore.v1.CommonProto.getDescriptor(),
          com.google.firestore.v1.DocumentProto.getDescriptor(),
          com.google.firestore.v1.QueryProto.getDescriptor(),
          com.google.firestore.v1.WriteProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.rpc.StatusProto.getDescriptor(),
        },
        assigner);
    internal_static_google_firestore_v1_GetDocumentRequest_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_google_firestore_v1_GetDocumentRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_firestore_v1_GetDocumentRequest_descriptor,
            new java.lang.String[] {
              "Name", "Mask", "Transaction", "ReadTime", "ConsistencySelector",
            });
    internal_static_google_firestore_v1_ListDocumentsRequest_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_google_firestore_v1_ListDocumentsRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_firestore_v1_ListDocumentsRequest_descriptor,
            new java.lang.String[] {
              "Parent",
              "CollectionId",
              "PageSize",
              "PageToken",
              "OrderBy",
              "Mask",
              "Transaction",
              "ReadTime",
              "ShowMissing",
              "ConsistencySelector",
            });
    internal_static_google_firestore_v1_ListDocumentsResponse_descriptor =
        getDescriptor().getMessageTypes().get(2);
    internal_static_google_firestore_v1_ListDocumentsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_firestore_v1_ListDocumentsResponse_descriptor,
            new java.lang.String[] {
              "Documents", "NextPageToken",
            });
    internal_static_google_firestore_v1_CreateDocumentRequest_descriptor =
        getDescriptor().getMessageTypes().get(3);
    internal_static_google_firestore_v1_CreateDocumentRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_firestore_v1_CreateDocumentRequest_descriptor,
            new java.lang.String[] {
              "Parent", "CollectionId", "DocumentId", "Document", "Mask",
            });
    internal_static_google_firestore_v1_UpdateDocumentRequest_descriptor =
        getDescriptor().getMessageTypes().get(4);
    internal_static_google_firestore_v1_UpdateDocumentRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_firestore_v1_UpdateDocumentRequest_descriptor,
            new java.lang.String[] {
              "Document", "UpdateMask", "Mask", "CurrentDocument",
            });
    internal_static_google_firestore_v1_DeleteDocumentRequest_descriptor =
        getDescriptor().getMessageTypes().get(5);
    internal_static_google_firestore_v1_DeleteDocumentRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_firestore_v1_DeleteDocumentRequest_descriptor,
            new java.lang.String[] {
              "Name", "CurrentDocument",
            });
    internal_static_google_firestore_v1_BatchGetDocumentsRequest_descriptor =
        getDescriptor().getMessageTypes().get(6);
    internal_static_google_firestore_v1_BatchGetDocumentsRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_firestore_v1_BatchGetDocumentsRequest_descriptor,
            new java.lang.String[] {
              "Database",
              "Documents",
              "Mask",
              "Transaction",
              "NewTransaction",
              "ReadTime",
              "ConsistencySelector",
            });
    internal_static_google_firestore_v1_BatchGetDocumentsResponse_descriptor =
        getDescriptor().getMessageTypes().get(7);
    internal_static_google_firestore_v1_BatchGetDocumentsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_firestore_v1_BatchGetDocumentsResponse_descriptor,
            new java.lang.String[] {
              "Found", "Missing", "Transaction", "ReadTime", "Result",
            });
    internal_static_google_firestore_v1_BeginTransactionRequest_descriptor =
        getDescriptor().getMessageTypes().get(8);
    internal_static_google_firestore_v1_BeginTransactionRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_firestore_v1_BeginTransactionRequest_descriptor,
            new java.lang.String[] {
              "Database", "Options",
            });
    internal_static_google_firestore_v1_BeginTransactionResponse_descriptor =
        getDescriptor().getMessageTypes().get(9);
    internal_static_google_firestore_v1_BeginTransactionResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_firestore_v1_BeginTransactionResponse_descriptor,
            new java.lang.String[] {
              "Transaction",
            });
    internal_static_google_firestore_v1_CommitRequest_descriptor =
        getDescriptor().getMessageTypes().get(10);
    internal_static_google_firestore_v1_CommitRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_firestore_v1_CommitRequest_descriptor,
            new java.lang.String[] {
              "Database", "Writes", "Transaction",
            });
    internal_static_google_firestore_v1_CommitResponse_descriptor =
        getDescriptor().getMessageTypes().get(11);
    internal_static_google_firestore_v1_CommitResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_firestore_v1_CommitResponse_descriptor,
            new java.lang.String[] {
              "WriteResults", "CommitTime",
            });
    internal_static_google_firestore_v1_RollbackRequest_descriptor =
        getDescriptor().getMessageTypes().get(12);
    internal_static_google_firestore_v1_RollbackRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_firestore_v1_RollbackRequest_descriptor,
            new java.lang.String[] {
              "Database", "Transaction",
            });
    internal_static_google_firestore_v1_RunQueryRequest_descriptor =
        getDescriptor().getMessageTypes().get(13);
    internal_static_google_firestore_v1_RunQueryRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_firestore_v1_RunQueryRequest_descriptor,
            new java.lang.String[] {
              "Parent",
              "StructuredQuery",
              "Transaction",
              "NewTransaction",
              "ReadTime",
              "QueryType",
              "ConsistencySelector",
            });
    internal_static_google_firestore_v1_RunQueryResponse_descriptor =
        getDescriptor().getMessageTypes().get(14);
    internal_static_google_firestore_v1_RunQueryResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_firestore_v1_RunQueryResponse_descriptor,
            new java.lang.String[] {
              "Transaction", "Document", "ReadTime", "SkippedResults",
            });
    internal_static_google_firestore_v1_WriteRequest_descriptor =
        getDescriptor().getMessageTypes().get(15);
    internal_static_google_firestore_v1_WriteRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_firestore_v1_WriteRequest_descriptor,
            new java.lang.String[] {
              "Database", "StreamId", "Writes", "StreamToken", "Labels",
            });
    internal_static_google_firestore_v1_WriteRequest_LabelsEntry_descriptor =
        internal_static_google_firestore_v1_WriteRequest_descriptor.getNestedTypes().get(0);
    internal_static_google_firestore_v1_WriteRequest_LabelsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_firestore_v1_WriteRequest_LabelsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_firestore_v1_WriteResponse_descriptor =
        getDescriptor().getMessageTypes().get(16);
    internal_static_google_firestore_v1_WriteResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_firestore_v1_WriteResponse_descriptor,
            new java.lang.String[] {
              "StreamId", "StreamToken", "WriteResults", "CommitTime",
            });
    internal_static_google_firestore_v1_ListenRequest_descriptor =
        getDescriptor().getMessageTypes().get(17);
    internal_static_google_firestore_v1_ListenRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_firestore_v1_ListenRequest_descriptor,
            new java.lang.String[] {
              "Database", "AddTarget", "RemoveTarget", "Labels", "TargetChange",
            });
    internal_static_google_firestore_v1_ListenRequest_LabelsEntry_descriptor =
        internal_static_google_firestore_v1_ListenRequest_descriptor.getNestedTypes().get(0);
    internal_static_google_firestore_v1_ListenRequest_LabelsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_firestore_v1_ListenRequest_LabelsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_firestore_v1_ListenResponse_descriptor =
        getDescriptor().getMessageTypes().get(18);
    internal_static_google_firestore_v1_ListenResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_firestore_v1_ListenResponse_descriptor,
            new java.lang.String[] {
              "TargetChange",
              "DocumentChange",
              "DocumentDelete",
              "DocumentRemove",
              "Filter",
              "ResponseType",
            });
    internal_static_google_firestore_v1_Target_descriptor =
        getDescriptor().getMessageTypes().get(19);
    internal_static_google_firestore_v1_Target_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_firestore_v1_Target_descriptor,
            new java.lang.String[] {
              "Query",
              "Documents",
              "ResumeToken",
              "ReadTime",
              "TargetId",
              "Once",
              "TargetType",
              "ResumeType",
            });
    internal_static_google_firestore_v1_Target_DocumentsTarget_descriptor =
        internal_static_google_firestore_v1_Target_descriptor.getNestedTypes().get(0);
    internal_static_google_firestore_v1_Target_DocumentsTarget_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_firestore_v1_Target_DocumentsTarget_descriptor,
            new java.lang.String[] {
              "Documents",
            });
    internal_static_google_firestore_v1_Target_QueryTarget_descriptor =
        internal_static_google_firestore_v1_Target_descriptor.getNestedTypes().get(1);
    internal_static_google_firestore_v1_Target_QueryTarget_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_firestore_v1_Target_QueryTarget_descriptor,
            new java.lang.String[] {
              "Parent", "StructuredQuery", "QueryType",
            });
    internal_static_google_firestore_v1_TargetChange_descriptor =
        getDescriptor().getMessageTypes().get(20);
    internal_static_google_firestore_v1_TargetChange_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_firestore_v1_TargetChange_descriptor,
            new java.lang.String[] {
              "TargetChangeType", "TargetIds", "Cause", "ResumeToken", "ReadTime",
            });
    internal_static_google_firestore_v1_ListCollectionIdsRequest_descriptor =
        getDescriptor().getMessageTypes().get(21);
    internal_static_google_firestore_v1_ListCollectionIdsRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_firestore_v1_ListCollectionIdsRequest_descriptor,
            new java.lang.String[] {
              "Parent", "PageSize", "PageToken",
            });
    internal_static_google_firestore_v1_ListCollectionIdsResponse_descriptor =
        getDescriptor().getMessageTypes().get(22);
    internal_static_google_firestore_v1_ListCollectionIdsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_firestore_v1_ListCollectionIdsResponse_descriptor,
            new java.lang.String[] {
              "CollectionIds", "NextPageToken",
            });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.ClientProto.defaultHost);
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.google.api.ClientProto.methodSignature);
    registry.add(com.google.api.ClientProto.oauthScopes);
    com.google.protobuf.Descriptors.FileDescriptor.internalUpdateFileDescriptor(
        descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.ClientProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.firestore.v1.CommonProto.getDescriptor();
    com.google.firestore.v1.DocumentProto.getDescriptor();
    com.google.firestore.v1.QueryProto.getDescriptor();
    com.google.firestore.v1.WriteProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.rpc.StatusProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
