// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/firestore/admin/v1/operation.proto
// Protobuf Java Version: 4.33.0

package com.google.firestore.admin.v1;

@com.google.protobuf.Generated
public interface ExportDocumentsResponseOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.firestore.admin.v1.ExportDocumentsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Location of the output files. This can be used to begin an import
   * into Cloud Firestore (this project or another project) after the operation
   * completes successfully.
   * </pre>
   *
   * <code>string output_uri_prefix = 1;</code>
   *
   * @return The outputUriPrefix.
   */
  java.lang.String getOutputUriPrefix();

  /**
   *
   *
   * <pre>
   * Location of the output files. This can be used to begin an import
   * into Cloud Firestore (this project or another project) after the operation
   * completes successfully.
   * </pre>
   *
   * <code>string output_uri_prefix = 1;</code>
   *
   * @return The bytes for outputUriPrefix.
   */
  com.google.protobuf.ByteString getOutputUriPrefixBytes();
}
