// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/firestore/admin/v1/firestore_admin.proto
// Protobuf Java Version: 4.33.0

package com.google.firestore.admin.v1;

@com.google.protobuf.Generated
public interface ListUserCredsResponseOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.firestore.admin.v1.ListUserCredsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * The user creds for the database.
   * </pre>
   *
   * <code>repeated .google.firestore.admin.v1.UserCreds user_creds = 1;</code>
   */
  java.util.List<com.google.firestore.admin.v1.UserCreds> getUserCredsList();

  /**
   *
   *
   * <pre>
   * The user creds for the database.
   * </pre>
   *
   * <code>repeated .google.firestore.admin.v1.UserCreds user_creds = 1;</code>
   */
  com.google.firestore.admin.v1.UserCreds getUserCreds(int index);

  /**
   *
   *
   * <pre>
   * The user creds for the database.
   * </pre>
   *
   * <code>repeated .google.firestore.admin.v1.UserCreds user_creds = 1;</code>
   */
  int getUserCredsCount();

  /**
   *
   *
   * <pre>
   * The user creds for the database.
   * </pre>
   *
   * <code>repeated .google.firestore.admin.v1.UserCreds user_creds = 1;</code>
   */
  java.util.List<? extends com.google.firestore.admin.v1.UserCredsOrBuilder>
      getUserCredsOrBuilderList();

  /**
   *
   *
   * <pre>
   * The user creds for the database.
   * </pre>
   *
   * <code>repeated .google.firestore.admin.v1.UserCreds user_creds = 1;</code>
   */
  com.google.firestore.admin.v1.UserCredsOrBuilder getUserCredsOrBuilder(int index);
}
