// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/firestore/admin/v1/firestore_admin.proto
// Protobuf Java Version: 4.33.0

package com.google.firestore.admin.v1;

@com.google.protobuf.Generated
public interface UpdateDatabaseRequestOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.firestore.admin.v1.UpdateDatabaseRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Required. The database to update.
   * </pre>
   *
   * <code>
   * .google.firestore.admin.v1.Database database = 1 [(.google.api.field_behavior) = REQUIRED];
   * </code>
   *
   * @return Whether the database field is set.
   */
  boolean hasDatabase();

  /**
   *
   *
   * <pre>
   * Required. The database to update.
   * </pre>
   *
   * <code>
   * .google.firestore.admin.v1.Database database = 1 [(.google.api.field_behavior) = REQUIRED];
   * </code>
   *
   * @return The database.
   */
  com.google.firestore.admin.v1.Database getDatabase();

  /**
   *
   *
   * <pre>
   * Required. The database to update.
   * </pre>
   *
   * <code>
   * .google.firestore.admin.v1.Database database = 1 [(.google.api.field_behavior) = REQUIRED];
   * </code>
   */
  com.google.firestore.admin.v1.DatabaseOrBuilder getDatabaseOrBuilder();

  /**
   *
   *
   * <pre>
   * The list of fields to be updated.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 2;</code>
   *
   * @return Whether the updateMask field is set.
   */
  boolean hasUpdateMask();

  /**
   *
   *
   * <pre>
   * The list of fields to be updated.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 2;</code>
   *
   * @return The updateMask.
   */
  com.google.protobuf.FieldMask getUpdateMask();

  /**
   *
   *
   * <pre>
   * The list of fields to be updated.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 2;</code>
   */
  com.google.protobuf.FieldMaskOrBuilder getUpdateMaskOrBuilder();
}
