// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/firestore/admin/v1/firestore_admin.proto
// Protobuf Java Version: 4.33.0

package com.google.firestore.admin.v1;

@com.google.protobuf.Generated
public interface UpdateDatabaseMetadataOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.firestore.admin.v1.UpdateDatabaseMetadata)
    com.google.protobuf.MessageOrBuilder {}
