// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/firestore/admin/v1/schedule.proto
// Protobuf Java Version: 4.33.0

package com.google.firestore.admin.v1;

@com.google.protobuf.Generated
public interface WeeklyRecurrenceOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.firestore.admin.v1.WeeklyRecurrence)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * The day of week to run.
   *
   * DAY_OF_WEEK_UNSPECIFIED is not allowed.
   * </pre>
   *
   * <code>.google.type.DayOfWeek day = 2;</code>
   *
   * @return The enum numeric value on the wire for day.
   */
  int getDayValue();

  /**
   *
   *
   * <pre>
   * The day of week to run.
   *
   * DAY_OF_WEEK_UNSPECIFIED is not allowed.
   * </pre>
   *
   * <code>.google.type.DayOfWeek day = 2;</code>
   *
   * @return The day.
   */
  com.google.type.DayOfWeek getDay();
}
