/*
 * Copyright 2019 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/firestore/v1beta1/firestore.proto

package com.google.firestore.v1beta1;

public interface CommitResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.firestore.v1beta1.CommitResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The result of applying the writes.
   * This i-th write result corresponds to the i-th write in the
   * request.
   * </pre>
   *
   * <code>repeated .google.firestore.v1beta1.WriteResult write_results = 1;</code>
   */
  java.util.List<com.google.firestore.v1beta1.WriteResult> 
      getWriteResultsList();
  /**
   * <pre>
   * The result of applying the writes.
   * This i-th write result corresponds to the i-th write in the
   * request.
   * </pre>
   *
   * <code>repeated .google.firestore.v1beta1.WriteResult write_results = 1;</code>
   */
  com.google.firestore.v1beta1.WriteResult getWriteResults(int index);
  /**
   * <pre>
   * The result of applying the writes.
   * This i-th write result corresponds to the i-th write in the
   * request.
   * </pre>
   *
   * <code>repeated .google.firestore.v1beta1.WriteResult write_results = 1;</code>
   */
  int getWriteResultsCount();
  /**
   * <pre>
   * The result of applying the writes.
   * This i-th write result corresponds to the i-th write in the
   * request.
   * </pre>
   *
   * <code>repeated .google.firestore.v1beta1.WriteResult write_results = 1;</code>
   */
  java.util.List<? extends com.google.firestore.v1beta1.WriteResultOrBuilder> 
      getWriteResultsOrBuilderList();
  /**
   * <pre>
   * The result of applying the writes.
   * This i-th write result corresponds to the i-th write in the
   * request.
   * </pre>
   *
   * <code>repeated .google.firestore.v1beta1.WriteResult write_results = 1;</code>
   */
  com.google.firestore.v1beta1.WriteResultOrBuilder getWriteResultsOrBuilder(
      int index);

  /**
   * <pre>
   * The time at which the commit occurred.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp commit_time = 2;</code>
   */
  boolean hasCommitTime();
  /**
   * <pre>
   * The time at which the commit occurred.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp commit_time = 2;</code>
   */
  com.google.protobuf.Timestamp getCommitTime();
  /**
   * <pre>
   * The time at which the commit occurred.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp commit_time = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCommitTimeOrBuilder();
}
