package com.google.cloud.firestore.pipeline.expressions;

import com.google.api.core.BetaApi;

/** An enumeration of the different types generated by the Firestore backend. */
@BetaApi
public enum Type {
  NULL,
  ARRAY,
  BOOLEAN,
  BYTES,
  TIMESTAMP,
  GEO_POINT,
  NUMBER,
  INT32,
  INT64,
  FLOAT64,
  DECIMAL128,
  MAP,
  REFERENCE,
  STRING,
  VECTOR,
  MAX_KEY,
  MIN_KEY,
  OBJECT_ID,
  REGEX,
  REQUEST_TIMESTAMP,
}
