/*
 * Copyright 2019 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: firestore/bundle.proto

package com.google.firestore.proto;

public final class BundleProto {
  private BundleProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_firestore_BundledQuery_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_firestore_BundledQuery_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_firestore_NamedQuery_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_firestore_NamedQuery_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_firestore_BundledDocumentMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_firestore_BundledDocumentMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_firestore_BundleMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_firestore_BundleMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_firestore_BundleElement_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_firestore_BundleElement_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026firestore/bundle.proto\022\tfirestore\032\"goo" +
      "gle/firestore/v1/document.proto\032\037google/" +
      "firestore/v1/query.proto\032\037google/protobu" +
      "f/timestamp.proto\"\307\001\n\014BundledQuery\022\016\n\006pa" +
      "rent\030\001 \001(\t\022@\n\020structured_query\030\002 \001(\0132$.g" +
      "oogle.firestore.v1.StructuredQueryH\000\0225\n\n" +
      "limit_type\030\003 \001(\0162!.firestore.BundledQuer" +
      "y.LimitType\" \n\tLimitType\022\t\n\005FIRST\020\000\022\010\n\004L" +
      "AST\020\001B\014\n\nquery_type\"y\n\nNamedQuery\022\014\n\004nam" +
      "e\030\001 \001(\t\022.\n\rbundled_query\030\002 \001(\0132\027.firesto" +
      "re.BundledQuery\022-\n\tread_time\030\003 \001(\0132\032.goo" +
      "gle.protobuf.Timestamp\"f\n\027BundledDocumen" +
      "tMetadata\022\014\n\004name\030\001 \001(\t\022-\n\tread_time\030\002 \001" +
      "(\0132\032.google.protobuf.Timestamp\022\016\n\006exists" +
      "\030\003 \001(\010\"\214\001\n\016BundleMetadata\022\n\n\002id\030\001 \001(\t\022/\n" +
      "\013create_time\030\002 \001(\0132\032.google.protobuf.Tim" +
      "estamp\022\017\n\007version\030\003 \001(\r\022\027\n\017total_documen" +
      "ts\030\004 \001(\r\022\023\n\013total_bytes\030\005 \001(\004\"\360\001\n\rBundle" +
      "Element\022-\n\010metadata\030\001 \001(\0132\031.firestore.Bu" +
      "ndleMetadataH\000\022,\n\013named_query\030\002 \001(\0132\025.fi" +
      "restore.NamedQueryH\000\022?\n\021document_metadat" +
      "a\030\003 \001(\0132\".firestore.BundledDocumentMetad" +
      "ataH\000\0221\n\010document\030\004 \001(\0132\035.google.firesto" +
      "re.v1.DocumentH\000B\016\n\014element_typeB\215\001\n\032com" +
      ".google.firestore.protoB\013BundleProtoP\001Z4" +
      "google.golang.org/genproto/firestore/pro" +
      "to;firestore\242\002\005FSTPB\252\002\017Firestore.Proto\312\002" +
      "\017Firestore\\Protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.firestore.v1.DocumentProto.getDescriptor(),
          com.google.firestore.v1.QueryProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_firestore_BundledQuery_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_firestore_BundledQuery_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_firestore_BundledQuery_descriptor,
        new java.lang.String[] { "Parent", "StructuredQuery", "LimitType", "QueryType", });
    internal_static_firestore_NamedQuery_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_firestore_NamedQuery_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_firestore_NamedQuery_descriptor,
        new java.lang.String[] { "Name", "BundledQuery", "ReadTime", });
    internal_static_firestore_BundledDocumentMetadata_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_firestore_BundledDocumentMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_firestore_BundledDocumentMetadata_descriptor,
        new java.lang.String[] { "Name", "ReadTime", "Exists", });
    internal_static_firestore_BundleMetadata_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_firestore_BundleMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_firestore_BundleMetadata_descriptor,
        new java.lang.String[] { "Id", "CreateTime", "Version", "TotalDocuments", "TotalBytes", });
    internal_static_firestore_BundleElement_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_firestore_BundleElement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_firestore_BundleElement_descriptor,
        new java.lang.String[] { "Metadata", "NamedQuery", "DocumentMetadata", "Document", "ElementType", });
    com.google.firestore.v1.DocumentProto.getDescriptor();
    com.google.firestore.v1.QueryProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
